import { ShieldAlert } from 'lucide-react'

export function Disclaimer({ compact = false }) {
  return (
    <aside className={`disclaimer ${compact ? 'py-4' : 'py-5'}`} aria-label="Medical disclaimer">
      <ShieldAlert className="mt-0.5 shrink-0 text-amber-700" size={20} aria-hidden="true" />
      <p className="text-sm leading-6 text-amber-950">
        <strong>Research use only.</strong> This application is developed for academic and research purposes. The predictions generated by the model are not a medical diagnosis and should not be used as a substitute for professional medical advice, diagnosis, or treatment.
      </p>
    </aside>
  )
}

